// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module MemoryBus(
  input         auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_ready,
  output        auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_valid,
  output [2:0]  auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_opcode,
                auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_param,
                auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_size,
  output [3:0]  auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_source,
  output [27:0] auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_address,
  output [7:0]  auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_mask,
  output [63:0] auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_data,
  output        auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_corrupt,
                auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_ready,
  input         auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_valid,
  input  [2:0]  auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_bits_opcode,
                auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_bits_size,
  input  [3:0]  auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_bits_source,
  input  [63:0] auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_bits_data,
  input         auto_coupler_to_bus_named_subsystem_obus_widget_out_a_ready,
  output        auto_coupler_to_bus_named_subsystem_obus_widget_out_a_valid,
  output [2:0]  auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_opcode,
                auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_param,
                auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_size,
  output [3:0]  auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_source,
  output [32:0] auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_address,
  output [7:0]  auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_mask,
  output [63:0] auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_data,
  output        auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_corrupt,
                auto_coupler_to_bus_named_subsystem_obus_widget_out_d_ready,
  input         auto_coupler_to_bus_named_subsystem_obus_widget_out_d_valid,
  input  [2:0]  auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_opcode,
  input  [1:0]  auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_param,
  input  [2:0]  auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_size,
  input  [3:0]  auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_source,
  input         auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_sink,
                auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_denied,
  input  [63:0] auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_data,
  input         auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_corrupt,
                auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_1_clock,
                auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_1_reset,
                auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_clock,
                auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_reset,
  output        auto_subsystem_mbus_clock_groups_out_member_subsystem_obus_0_clock,
                auto_subsystem_mbus_clock_groups_out_member_subsystem_obus_0_reset,
  input  [2:0]  auto_bus_xing_in_a_mem_0_opcode,
                auto_bus_xing_in_a_mem_0_param,
                auto_bus_xing_in_a_mem_0_size,
  input  [3:0]  auto_bus_xing_in_a_mem_0_source,
  input  [32:0] auto_bus_xing_in_a_mem_0_address,
  input  [7:0]  auto_bus_xing_in_a_mem_0_mask,
  input  [63:0] auto_bus_xing_in_a_mem_0_data,
  input         auto_bus_xing_in_a_mem_0_corrupt,
  input  [2:0]  auto_bus_xing_in_a_mem_1_opcode,
                auto_bus_xing_in_a_mem_1_param,
                auto_bus_xing_in_a_mem_1_size,
  input  [3:0]  auto_bus_xing_in_a_mem_1_source,
  input  [32:0] auto_bus_xing_in_a_mem_1_address,
  input  [7:0]  auto_bus_xing_in_a_mem_1_mask,
  input  [63:0] auto_bus_xing_in_a_mem_1_data,
  input         auto_bus_xing_in_a_mem_1_corrupt,
  input  [2:0]  auto_bus_xing_in_a_mem_2_opcode,
                auto_bus_xing_in_a_mem_2_param,
                auto_bus_xing_in_a_mem_2_size,
  input  [3:0]  auto_bus_xing_in_a_mem_2_source,
  input  [32:0] auto_bus_xing_in_a_mem_2_address,
  input  [7:0]  auto_bus_xing_in_a_mem_2_mask,
  input  [63:0] auto_bus_xing_in_a_mem_2_data,
  input         auto_bus_xing_in_a_mem_2_corrupt,
  input  [2:0]  auto_bus_xing_in_a_mem_3_opcode,
                auto_bus_xing_in_a_mem_3_param,
                auto_bus_xing_in_a_mem_3_size,
  input  [3:0]  auto_bus_xing_in_a_mem_3_source,
  input  [32:0] auto_bus_xing_in_a_mem_3_address,
  input  [7:0]  auto_bus_xing_in_a_mem_3_mask,
  input  [63:0] auto_bus_xing_in_a_mem_3_data,
  input         auto_bus_xing_in_a_mem_3_corrupt,
  input  [2:0]  auto_bus_xing_in_a_mem_4_opcode,
                auto_bus_xing_in_a_mem_4_param,
                auto_bus_xing_in_a_mem_4_size,
  input  [3:0]  auto_bus_xing_in_a_mem_4_source,
  input  [32:0] auto_bus_xing_in_a_mem_4_address,
  input  [7:0]  auto_bus_xing_in_a_mem_4_mask,
  input  [63:0] auto_bus_xing_in_a_mem_4_data,
  input         auto_bus_xing_in_a_mem_4_corrupt,
  input  [2:0]  auto_bus_xing_in_a_mem_5_opcode,
                auto_bus_xing_in_a_mem_5_param,
                auto_bus_xing_in_a_mem_5_size,
  input  [3:0]  auto_bus_xing_in_a_mem_5_source,
  input  [32:0] auto_bus_xing_in_a_mem_5_address,
  input  [7:0]  auto_bus_xing_in_a_mem_5_mask,
  input  [63:0] auto_bus_xing_in_a_mem_5_data,
  input         auto_bus_xing_in_a_mem_5_corrupt,
  input  [2:0]  auto_bus_xing_in_a_mem_6_opcode,
                auto_bus_xing_in_a_mem_6_param,
                auto_bus_xing_in_a_mem_6_size,
  input  [3:0]  auto_bus_xing_in_a_mem_6_source,
  input  [32:0] auto_bus_xing_in_a_mem_6_address,
  input  [7:0]  auto_bus_xing_in_a_mem_6_mask,
  input  [63:0] auto_bus_xing_in_a_mem_6_data,
  input         auto_bus_xing_in_a_mem_6_corrupt,
  input  [2:0]  auto_bus_xing_in_a_mem_7_opcode,
                auto_bus_xing_in_a_mem_7_param,
                auto_bus_xing_in_a_mem_7_size,
  input  [3:0]  auto_bus_xing_in_a_mem_7_source,
  input  [32:0] auto_bus_xing_in_a_mem_7_address,
  input  [7:0]  auto_bus_xing_in_a_mem_7_mask,
  input  [63:0] auto_bus_xing_in_a_mem_7_data,
  input         auto_bus_xing_in_a_mem_7_corrupt,
  output [3:0]  auto_bus_xing_in_a_ridx,
  input  [3:0]  auto_bus_xing_in_a_widx,
  output        auto_bus_xing_in_a_safe_ridx_valid,
  input         auto_bus_xing_in_a_safe_widx_valid,
                auto_bus_xing_in_a_safe_source_reset_n,
  output        auto_bus_xing_in_a_safe_sink_reset_n,
  output [2:0]  auto_bus_xing_in_d_mem_0_opcode,
  output [1:0]  auto_bus_xing_in_d_mem_0_param,
  output [2:0]  auto_bus_xing_in_d_mem_0_size,
  output [3:0]  auto_bus_xing_in_d_mem_0_source,
  output        auto_bus_xing_in_d_mem_0_sink,
                auto_bus_xing_in_d_mem_0_denied,
  output [63:0] auto_bus_xing_in_d_mem_0_data,
  output        auto_bus_xing_in_d_mem_0_corrupt,
  output [2:0]  auto_bus_xing_in_d_mem_1_opcode,
  output [1:0]  auto_bus_xing_in_d_mem_1_param,
  output [2:0]  auto_bus_xing_in_d_mem_1_size,
  output [3:0]  auto_bus_xing_in_d_mem_1_source,
  output        auto_bus_xing_in_d_mem_1_sink,
                auto_bus_xing_in_d_mem_1_denied,
  output [63:0] auto_bus_xing_in_d_mem_1_data,
  output        auto_bus_xing_in_d_mem_1_corrupt,
  output [2:0]  auto_bus_xing_in_d_mem_2_opcode,
  output [1:0]  auto_bus_xing_in_d_mem_2_param,
  output [2:0]  auto_bus_xing_in_d_mem_2_size,
  output [3:0]  auto_bus_xing_in_d_mem_2_source,
  output        auto_bus_xing_in_d_mem_2_sink,
                auto_bus_xing_in_d_mem_2_denied,
  output [63:0] auto_bus_xing_in_d_mem_2_data,
  output        auto_bus_xing_in_d_mem_2_corrupt,
  output [2:0]  auto_bus_xing_in_d_mem_3_opcode,
  output [1:0]  auto_bus_xing_in_d_mem_3_param,
  output [2:0]  auto_bus_xing_in_d_mem_3_size,
  output [3:0]  auto_bus_xing_in_d_mem_3_source,
  output        auto_bus_xing_in_d_mem_3_sink,
                auto_bus_xing_in_d_mem_3_denied,
  output [63:0] auto_bus_xing_in_d_mem_3_data,
  output        auto_bus_xing_in_d_mem_3_corrupt,
  output [2:0]  auto_bus_xing_in_d_mem_4_opcode,
  output [1:0]  auto_bus_xing_in_d_mem_4_param,
  output [2:0]  auto_bus_xing_in_d_mem_4_size,
  output [3:0]  auto_bus_xing_in_d_mem_4_source,
  output        auto_bus_xing_in_d_mem_4_sink,
                auto_bus_xing_in_d_mem_4_denied,
  output [63:0] auto_bus_xing_in_d_mem_4_data,
  output        auto_bus_xing_in_d_mem_4_corrupt,
  output [2:0]  auto_bus_xing_in_d_mem_5_opcode,
  output [1:0]  auto_bus_xing_in_d_mem_5_param,
  output [2:0]  auto_bus_xing_in_d_mem_5_size,
  output [3:0]  auto_bus_xing_in_d_mem_5_source,
  output        auto_bus_xing_in_d_mem_5_sink,
                auto_bus_xing_in_d_mem_5_denied,
  output [63:0] auto_bus_xing_in_d_mem_5_data,
  output        auto_bus_xing_in_d_mem_5_corrupt,
  output [2:0]  auto_bus_xing_in_d_mem_6_opcode,
  output [1:0]  auto_bus_xing_in_d_mem_6_param,
  output [2:0]  auto_bus_xing_in_d_mem_6_size,
  output [3:0]  auto_bus_xing_in_d_mem_6_source,
  output        auto_bus_xing_in_d_mem_6_sink,
                auto_bus_xing_in_d_mem_6_denied,
  output [63:0] auto_bus_xing_in_d_mem_6_data,
  output        auto_bus_xing_in_d_mem_6_corrupt,
  output [2:0]  auto_bus_xing_in_d_mem_7_opcode,
  output [1:0]  auto_bus_xing_in_d_mem_7_param,
  output [2:0]  auto_bus_xing_in_d_mem_7_size,
  output [3:0]  auto_bus_xing_in_d_mem_7_source,
  output        auto_bus_xing_in_d_mem_7_sink,
                auto_bus_xing_in_d_mem_7_denied,
  output [63:0] auto_bus_xing_in_d_mem_7_data,
  output        auto_bus_xing_in_d_mem_7_corrupt,
  input  [3:0]  auto_bus_xing_in_d_ridx,
  output [3:0]  auto_bus_xing_in_d_widx,
  input         auto_bus_xing_in_d_safe_ridx_valid,
  output        auto_bus_xing_in_d_safe_widx_valid,
                auto_bus_xing_in_d_safe_source_reset_n,
  input         auto_bus_xing_in_d_safe_sink_reset_n
);

  wire        _asink_auto_out_a_valid;
  wire [2:0]  _asink_auto_out_a_bits_opcode;
  wire [2:0]  _asink_auto_out_a_bits_param;
  wire [2:0]  _asink_auto_out_a_bits_size;
  wire [3:0]  _asink_auto_out_a_bits_source;
  wire [32:0] _asink_auto_out_a_bits_address;
  wire [7:0]  _asink_auto_out_a_bits_mask;
  wire [63:0] _asink_auto_out_a_bits_data;
  wire        _asink_auto_out_a_bits_corrupt;
  wire        _asink_auto_out_d_ready;
  wire        _picker_auto_in_1_a_ready;
  wire        _picker_auto_in_1_d_valid;
  wire [2:0]  _picker_auto_in_1_d_bits_opcode;
  wire [2:0]  _picker_auto_in_1_d_bits_size;
  wire [3:0]  _picker_auto_in_1_d_bits_source;
  wire [63:0] _picker_auto_in_1_d_bits_data;
  wire        _picker_auto_in_0_a_ready;
  wire        _picker_auto_in_0_d_valid;
  wire [2:0]  _picker_auto_in_0_d_bits_opcode;
  wire [1:0]  _picker_auto_in_0_d_bits_param;
  wire [2:0]  _picker_auto_in_0_d_bits_size;
  wire [3:0]  _picker_auto_in_0_d_bits_source;
  wire        _picker_auto_in_0_d_bits_sink;
  wire        _picker_auto_in_0_d_bits_denied;
  wire [63:0] _picker_auto_in_0_d_bits_data;
  wire        _picker_auto_in_0_d_bits_corrupt;
  wire        _fixer_auto_in_a_ready;
  wire        _fixer_auto_in_d_valid;
  wire [2:0]  _fixer_auto_in_d_bits_opcode;
  wire [1:0]  _fixer_auto_in_d_bits_param;
  wire [2:0]  _fixer_auto_in_d_bits_size;
  wire [3:0]  _fixer_auto_in_d_bits_source;
  wire        _fixer_auto_in_d_bits_sink;
  wire        _fixer_auto_in_d_bits_denied;
  wire [63:0] _fixer_auto_in_d_bits_data;
  wire        _fixer_auto_in_d_bits_corrupt;
  wire        _fixer_auto_out_a_valid;
  wire [2:0]  _fixer_auto_out_a_bits_opcode;
  wire [2:0]  _fixer_auto_out_a_bits_param;
  wire [2:0]  _fixer_auto_out_a_bits_size;
  wire [3:0]  _fixer_auto_out_a_bits_source;
  wire [32:0] _fixer_auto_out_a_bits_address;
  wire [7:0]  _fixer_auto_out_a_bits_mask;
  wire [63:0] _fixer_auto_out_a_bits_data;
  wire        _fixer_auto_out_a_bits_corrupt;
  wire        _fixer_auto_out_d_ready;
  wire        _subsystem_mbus_xbar_auto_in_a_ready;
  wire        _subsystem_mbus_xbar_auto_in_d_valid;
  wire [2:0]  _subsystem_mbus_xbar_auto_in_d_bits_opcode;
  wire [1:0]  _subsystem_mbus_xbar_auto_in_d_bits_param;
  wire [2:0]  _subsystem_mbus_xbar_auto_in_d_bits_size;
  wire [3:0]  _subsystem_mbus_xbar_auto_in_d_bits_source;
  wire        _subsystem_mbus_xbar_auto_in_d_bits_sink;
  wire        _subsystem_mbus_xbar_auto_in_d_bits_denied;
  wire [63:0] _subsystem_mbus_xbar_auto_in_d_bits_data;
  wire        _subsystem_mbus_xbar_auto_in_d_bits_corrupt;
  wire        _subsystem_mbus_xbar_auto_out_1_a_valid;
  wire [2:0]  _subsystem_mbus_xbar_auto_out_1_a_bits_opcode;
  wire [2:0]  _subsystem_mbus_xbar_auto_out_1_a_bits_param;
  wire [2:0]  _subsystem_mbus_xbar_auto_out_1_a_bits_size;
  wire [3:0]  _subsystem_mbus_xbar_auto_out_1_a_bits_source;
  wire [27:0] _subsystem_mbus_xbar_auto_out_1_a_bits_address;
  wire [7:0]  _subsystem_mbus_xbar_auto_out_1_a_bits_mask;
  wire [63:0] _subsystem_mbus_xbar_auto_out_1_a_bits_data;
  wire        _subsystem_mbus_xbar_auto_out_1_a_bits_corrupt;
  wire        _subsystem_mbus_xbar_auto_out_1_d_ready;
  wire        _subsystem_mbus_xbar_auto_out_0_a_valid;
  wire [2:0]  _subsystem_mbus_xbar_auto_out_0_a_bits_opcode;
  wire [2:0]  _subsystem_mbus_xbar_auto_out_0_a_bits_param;
  wire [2:0]  _subsystem_mbus_xbar_auto_out_0_a_bits_size;
  wire [3:0]  _subsystem_mbus_xbar_auto_out_0_a_bits_source;
  wire [32:0] _subsystem_mbus_xbar_auto_out_0_a_bits_address;
  wire [7:0]  _subsystem_mbus_xbar_auto_out_0_a_bits_mask;
  wire [63:0] _subsystem_mbus_xbar_auto_out_0_a_bits_data;
  wire        _subsystem_mbus_xbar_auto_out_0_a_bits_corrupt;
  wire        _subsystem_mbus_xbar_auto_out_0_d_ready;
  TLXbar_6 subsystem_mbus_xbar (
    .clock                     (auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_clock),
    .reset                     (auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_reset),
    .auto_in_a_ready           (_subsystem_mbus_xbar_auto_in_a_ready),
    .auto_in_a_valid           (_fixer_auto_out_a_valid),
    .auto_in_a_bits_opcode     (_fixer_auto_out_a_bits_opcode),
    .auto_in_a_bits_param      (_fixer_auto_out_a_bits_param),
    .auto_in_a_bits_size       (_fixer_auto_out_a_bits_size),
    .auto_in_a_bits_source     (_fixer_auto_out_a_bits_source),
    .auto_in_a_bits_address    (_fixer_auto_out_a_bits_address),
    .auto_in_a_bits_mask       (_fixer_auto_out_a_bits_mask),
    .auto_in_a_bits_data       (_fixer_auto_out_a_bits_data),
    .auto_in_a_bits_corrupt    (_fixer_auto_out_a_bits_corrupt),
    .auto_in_d_ready           (_fixer_auto_out_d_ready),
    .auto_in_d_valid           (_subsystem_mbus_xbar_auto_in_d_valid),
    .auto_in_d_bits_opcode     (_subsystem_mbus_xbar_auto_in_d_bits_opcode),
    .auto_in_d_bits_param      (_subsystem_mbus_xbar_auto_in_d_bits_param),
    .auto_in_d_bits_size       (_subsystem_mbus_xbar_auto_in_d_bits_size),
    .auto_in_d_bits_source     (_subsystem_mbus_xbar_auto_in_d_bits_source),
    .auto_in_d_bits_sink       (_subsystem_mbus_xbar_auto_in_d_bits_sink),
    .auto_in_d_bits_denied     (_subsystem_mbus_xbar_auto_in_d_bits_denied),
    .auto_in_d_bits_data       (_subsystem_mbus_xbar_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt    (_subsystem_mbus_xbar_auto_in_d_bits_corrupt),
    .auto_out_1_a_ready        (_picker_auto_in_1_a_ready),
    .auto_out_1_a_valid        (_subsystem_mbus_xbar_auto_out_1_a_valid),
    .auto_out_1_a_bits_opcode  (_subsystem_mbus_xbar_auto_out_1_a_bits_opcode),
    .auto_out_1_a_bits_param   (_subsystem_mbus_xbar_auto_out_1_a_bits_param),
    .auto_out_1_a_bits_size    (_subsystem_mbus_xbar_auto_out_1_a_bits_size),
    .auto_out_1_a_bits_source  (_subsystem_mbus_xbar_auto_out_1_a_bits_source),
    .auto_out_1_a_bits_address (_subsystem_mbus_xbar_auto_out_1_a_bits_address),
    .auto_out_1_a_bits_mask    (_subsystem_mbus_xbar_auto_out_1_a_bits_mask),
    .auto_out_1_a_bits_data    (_subsystem_mbus_xbar_auto_out_1_a_bits_data),
    .auto_out_1_a_bits_corrupt (_subsystem_mbus_xbar_auto_out_1_a_bits_corrupt),
    .auto_out_1_d_ready        (_subsystem_mbus_xbar_auto_out_1_d_ready),
    .auto_out_1_d_valid        (_picker_auto_in_1_d_valid),
    .auto_out_1_d_bits_opcode  (_picker_auto_in_1_d_bits_opcode),
    .auto_out_1_d_bits_size    (_picker_auto_in_1_d_bits_size),
    .auto_out_1_d_bits_source  (_picker_auto_in_1_d_bits_source),
    .auto_out_1_d_bits_data    (_picker_auto_in_1_d_bits_data),
    .auto_out_0_a_ready        (_picker_auto_in_0_a_ready),
    .auto_out_0_a_valid        (_subsystem_mbus_xbar_auto_out_0_a_valid),
    .auto_out_0_a_bits_opcode  (_subsystem_mbus_xbar_auto_out_0_a_bits_opcode),
    .auto_out_0_a_bits_param   (_subsystem_mbus_xbar_auto_out_0_a_bits_param),
    .auto_out_0_a_bits_size    (_subsystem_mbus_xbar_auto_out_0_a_bits_size),
    .auto_out_0_a_bits_source  (_subsystem_mbus_xbar_auto_out_0_a_bits_source),
    .auto_out_0_a_bits_address (_subsystem_mbus_xbar_auto_out_0_a_bits_address),
    .auto_out_0_a_bits_mask    (_subsystem_mbus_xbar_auto_out_0_a_bits_mask),
    .auto_out_0_a_bits_data    (_subsystem_mbus_xbar_auto_out_0_a_bits_data),
    .auto_out_0_a_bits_corrupt (_subsystem_mbus_xbar_auto_out_0_a_bits_corrupt),
    .auto_out_0_d_ready        (_subsystem_mbus_xbar_auto_out_0_d_ready),
    .auto_out_0_d_valid        (_picker_auto_in_0_d_valid),
    .auto_out_0_d_bits_opcode  (_picker_auto_in_0_d_bits_opcode),
    .auto_out_0_d_bits_param   (_picker_auto_in_0_d_bits_param),
    .auto_out_0_d_bits_size    (_picker_auto_in_0_d_bits_size),
    .auto_out_0_d_bits_source  (_picker_auto_in_0_d_bits_source),
    .auto_out_0_d_bits_sink    (_picker_auto_in_0_d_bits_sink),
    .auto_out_0_d_bits_denied  (_picker_auto_in_0_d_bits_denied),
    .auto_out_0_d_bits_data    (_picker_auto_in_0_d_bits_data),
    .auto_out_0_d_bits_corrupt (_picker_auto_in_0_d_bits_corrupt)
  );
  TLFIFOFixer_4 fixer (
    .clock                   (auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_clock),
    .reset                   (auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_reset),
    .auto_in_a_ready         (_fixer_auto_in_a_ready),
    .auto_in_a_valid         (_asink_auto_out_a_valid),
    .auto_in_a_bits_opcode   (_asink_auto_out_a_bits_opcode),
    .auto_in_a_bits_param    (_asink_auto_out_a_bits_param),
    .auto_in_a_bits_size     (_asink_auto_out_a_bits_size),
    .auto_in_a_bits_source   (_asink_auto_out_a_bits_source),
    .auto_in_a_bits_address  (_asink_auto_out_a_bits_address),
    .auto_in_a_bits_mask     (_asink_auto_out_a_bits_mask),
    .auto_in_a_bits_data     (_asink_auto_out_a_bits_data),
    .auto_in_a_bits_corrupt  (_asink_auto_out_a_bits_corrupt),
    .auto_in_d_ready         (_asink_auto_out_d_ready),
    .auto_in_d_valid         (_fixer_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_fixer_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_fixer_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_fixer_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_fixer_auto_in_d_bits_source),
    .auto_in_d_bits_sink     (_fixer_auto_in_d_bits_sink),
    .auto_in_d_bits_denied   (_fixer_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_fixer_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_fixer_auto_in_d_bits_corrupt),
    .auto_out_a_ready        (_subsystem_mbus_xbar_auto_in_a_ready),
    .auto_out_a_valid        (_fixer_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_fixer_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_fixer_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_fixer_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_fixer_auto_out_a_bits_source),
    .auto_out_a_bits_address (_fixer_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_fixer_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_fixer_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt (_fixer_auto_out_a_bits_corrupt),
    .auto_out_d_ready        (_fixer_auto_out_d_ready),
    .auto_out_d_valid        (_subsystem_mbus_xbar_auto_in_d_valid),
    .auto_out_d_bits_opcode  (_subsystem_mbus_xbar_auto_in_d_bits_opcode),
    .auto_out_d_bits_param   (_subsystem_mbus_xbar_auto_in_d_bits_param),
    .auto_out_d_bits_size    (_subsystem_mbus_xbar_auto_in_d_bits_size),
    .auto_out_d_bits_source  (_subsystem_mbus_xbar_auto_in_d_bits_source),
    .auto_out_d_bits_sink    (_subsystem_mbus_xbar_auto_in_d_bits_sink),
    .auto_out_d_bits_denied  (_subsystem_mbus_xbar_auto_in_d_bits_denied),
    .auto_out_d_bits_data    (_subsystem_mbus_xbar_auto_in_d_bits_data),
    .auto_out_d_bits_corrupt (_subsystem_mbus_xbar_auto_in_d_bits_corrupt)
  );
  ProbePicker picker (
    .clock                     (auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_clock),
    .reset                     (auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_reset),
    .auto_in_1_a_ready         (_picker_auto_in_1_a_ready),
    .auto_in_1_a_valid         (_subsystem_mbus_xbar_auto_out_1_a_valid),
    .auto_in_1_a_bits_opcode   (_subsystem_mbus_xbar_auto_out_1_a_bits_opcode),
    .auto_in_1_a_bits_param    (_subsystem_mbus_xbar_auto_out_1_a_bits_param),
    .auto_in_1_a_bits_size     (_subsystem_mbus_xbar_auto_out_1_a_bits_size),
    .auto_in_1_a_bits_source   (_subsystem_mbus_xbar_auto_out_1_a_bits_source),
    .auto_in_1_a_bits_address  (_subsystem_mbus_xbar_auto_out_1_a_bits_address),
    .auto_in_1_a_bits_mask     (_subsystem_mbus_xbar_auto_out_1_a_bits_mask),
    .auto_in_1_a_bits_data     (_subsystem_mbus_xbar_auto_out_1_a_bits_data),
    .auto_in_1_a_bits_corrupt  (_subsystem_mbus_xbar_auto_out_1_a_bits_corrupt),
    .auto_in_1_d_ready         (_subsystem_mbus_xbar_auto_out_1_d_ready),
    .auto_in_1_d_valid         (_picker_auto_in_1_d_valid),
    .auto_in_1_d_bits_opcode   (_picker_auto_in_1_d_bits_opcode),
    .auto_in_1_d_bits_size     (_picker_auto_in_1_d_bits_size),
    .auto_in_1_d_bits_source   (_picker_auto_in_1_d_bits_source),
    .auto_in_1_d_bits_data     (_picker_auto_in_1_d_bits_data),
    .auto_in_0_a_ready         (_picker_auto_in_0_a_ready),
    .auto_in_0_a_valid         (_subsystem_mbus_xbar_auto_out_0_a_valid),
    .auto_in_0_a_bits_opcode   (_subsystem_mbus_xbar_auto_out_0_a_bits_opcode),
    .auto_in_0_a_bits_param    (_subsystem_mbus_xbar_auto_out_0_a_bits_param),
    .auto_in_0_a_bits_size     (_subsystem_mbus_xbar_auto_out_0_a_bits_size),
    .auto_in_0_a_bits_source   (_subsystem_mbus_xbar_auto_out_0_a_bits_source),
    .auto_in_0_a_bits_address  (_subsystem_mbus_xbar_auto_out_0_a_bits_address),
    .auto_in_0_a_bits_mask     (_subsystem_mbus_xbar_auto_out_0_a_bits_mask),
    .auto_in_0_a_bits_data     (_subsystem_mbus_xbar_auto_out_0_a_bits_data),
    .auto_in_0_a_bits_corrupt  (_subsystem_mbus_xbar_auto_out_0_a_bits_corrupt),
    .auto_in_0_d_ready         (_subsystem_mbus_xbar_auto_out_0_d_ready),
    .auto_in_0_d_valid         (_picker_auto_in_0_d_valid),
    .auto_in_0_d_bits_opcode   (_picker_auto_in_0_d_bits_opcode),
    .auto_in_0_d_bits_param    (_picker_auto_in_0_d_bits_param),
    .auto_in_0_d_bits_size     (_picker_auto_in_0_d_bits_size),
    .auto_in_0_d_bits_source   (_picker_auto_in_0_d_bits_source),
    .auto_in_0_d_bits_sink     (_picker_auto_in_0_d_bits_sink),
    .auto_in_0_d_bits_denied   (_picker_auto_in_0_d_bits_denied),
    .auto_in_0_d_bits_data     (_picker_auto_in_0_d_bits_data),
    .auto_in_0_d_bits_corrupt  (_picker_auto_in_0_d_bits_corrupt),
    .auto_out_1_a_ready        (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_ready),
    .auto_out_1_a_valid        (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_valid),
    .auto_out_1_a_bits_opcode  (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_opcode),
    .auto_out_1_a_bits_param   (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_param),
    .auto_out_1_a_bits_size    (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_size),
    .auto_out_1_a_bits_source  (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_source),
    .auto_out_1_a_bits_address (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_address),
    .auto_out_1_a_bits_mask    (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_mask),
    .auto_out_1_a_bits_data    (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_data),
    .auto_out_1_a_bits_corrupt (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_a_bits_corrupt),
    .auto_out_1_d_ready        (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_ready),
    .auto_out_1_d_valid        (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_valid),
    .auto_out_1_d_bits_opcode  (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_bits_opcode),
    .auto_out_1_d_bits_size    (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_bits_size),
    .auto_out_1_d_bits_source  (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_bits_source),
    .auto_out_1_d_bits_data    (auto_coupler_to_subsystem_mbusscratchpad00_buffer_out_d_bits_data),
    .auto_out_0_a_ready        (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_ready),
    .auto_out_0_a_valid        (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_valid),
    .auto_out_0_a_bits_opcode  (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_opcode),
    .auto_out_0_a_bits_param   (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_param),
    .auto_out_0_a_bits_size    (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_size),
    .auto_out_0_a_bits_source  (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_source),
    .auto_out_0_a_bits_address (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_address),
    .auto_out_0_a_bits_mask    (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_mask),
    .auto_out_0_a_bits_data    (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_data),
    .auto_out_0_a_bits_corrupt (auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_corrupt),
    .auto_out_0_d_ready        (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_ready),
    .auto_out_0_d_valid        (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_valid),
    .auto_out_0_d_bits_opcode  (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_opcode),
    .auto_out_0_d_bits_param   (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_param),
    .auto_out_0_d_bits_size    (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_size),
    .auto_out_0_d_bits_source  (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_source),
    .auto_out_0_d_bits_sink    (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_sink),
    .auto_out_0_d_bits_denied  (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_denied),
    .auto_out_0_d_bits_data    (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_data),
    .auto_out_0_d_bits_corrupt (auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_corrupt)
  );
  TLAsyncCrossingSink_4 asink (
    .clock                         (auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_clock),
    .reset                         (auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_reset),
    .auto_in_a_mem_0_opcode        (auto_bus_xing_in_a_mem_0_opcode),
    .auto_in_a_mem_0_param         (auto_bus_xing_in_a_mem_0_param),
    .auto_in_a_mem_0_size          (auto_bus_xing_in_a_mem_0_size),
    .auto_in_a_mem_0_source        (auto_bus_xing_in_a_mem_0_source),
    .auto_in_a_mem_0_address       (auto_bus_xing_in_a_mem_0_address),
    .auto_in_a_mem_0_mask          (auto_bus_xing_in_a_mem_0_mask),
    .auto_in_a_mem_0_data          (auto_bus_xing_in_a_mem_0_data),
    .auto_in_a_mem_0_corrupt       (auto_bus_xing_in_a_mem_0_corrupt),
    .auto_in_a_mem_1_opcode        (auto_bus_xing_in_a_mem_1_opcode),
    .auto_in_a_mem_1_param         (auto_bus_xing_in_a_mem_1_param),
    .auto_in_a_mem_1_size          (auto_bus_xing_in_a_mem_1_size),
    .auto_in_a_mem_1_source        (auto_bus_xing_in_a_mem_1_source),
    .auto_in_a_mem_1_address       (auto_bus_xing_in_a_mem_1_address),
    .auto_in_a_mem_1_mask          (auto_bus_xing_in_a_mem_1_mask),
    .auto_in_a_mem_1_data          (auto_bus_xing_in_a_mem_1_data),
    .auto_in_a_mem_1_corrupt       (auto_bus_xing_in_a_mem_1_corrupt),
    .auto_in_a_mem_2_opcode        (auto_bus_xing_in_a_mem_2_opcode),
    .auto_in_a_mem_2_param         (auto_bus_xing_in_a_mem_2_param),
    .auto_in_a_mem_2_size          (auto_bus_xing_in_a_mem_2_size),
    .auto_in_a_mem_2_source        (auto_bus_xing_in_a_mem_2_source),
    .auto_in_a_mem_2_address       (auto_bus_xing_in_a_mem_2_address),
    .auto_in_a_mem_2_mask          (auto_bus_xing_in_a_mem_2_mask),
    .auto_in_a_mem_2_data          (auto_bus_xing_in_a_mem_2_data),
    .auto_in_a_mem_2_corrupt       (auto_bus_xing_in_a_mem_2_corrupt),
    .auto_in_a_mem_3_opcode        (auto_bus_xing_in_a_mem_3_opcode),
    .auto_in_a_mem_3_param         (auto_bus_xing_in_a_mem_3_param),
    .auto_in_a_mem_3_size          (auto_bus_xing_in_a_mem_3_size),
    .auto_in_a_mem_3_source        (auto_bus_xing_in_a_mem_3_source),
    .auto_in_a_mem_3_address       (auto_bus_xing_in_a_mem_3_address),
    .auto_in_a_mem_3_mask          (auto_bus_xing_in_a_mem_3_mask),
    .auto_in_a_mem_3_data          (auto_bus_xing_in_a_mem_3_data),
    .auto_in_a_mem_3_corrupt       (auto_bus_xing_in_a_mem_3_corrupt),
    .auto_in_a_mem_4_opcode        (auto_bus_xing_in_a_mem_4_opcode),
    .auto_in_a_mem_4_param         (auto_bus_xing_in_a_mem_4_param),
    .auto_in_a_mem_4_size          (auto_bus_xing_in_a_mem_4_size),
    .auto_in_a_mem_4_source        (auto_bus_xing_in_a_mem_4_source),
    .auto_in_a_mem_4_address       (auto_bus_xing_in_a_mem_4_address),
    .auto_in_a_mem_4_mask          (auto_bus_xing_in_a_mem_4_mask),
    .auto_in_a_mem_4_data          (auto_bus_xing_in_a_mem_4_data),
    .auto_in_a_mem_4_corrupt       (auto_bus_xing_in_a_mem_4_corrupt),
    .auto_in_a_mem_5_opcode        (auto_bus_xing_in_a_mem_5_opcode),
    .auto_in_a_mem_5_param         (auto_bus_xing_in_a_mem_5_param),
    .auto_in_a_mem_5_size          (auto_bus_xing_in_a_mem_5_size),
    .auto_in_a_mem_5_source        (auto_bus_xing_in_a_mem_5_source),
    .auto_in_a_mem_5_address       (auto_bus_xing_in_a_mem_5_address),
    .auto_in_a_mem_5_mask          (auto_bus_xing_in_a_mem_5_mask),
    .auto_in_a_mem_5_data          (auto_bus_xing_in_a_mem_5_data),
    .auto_in_a_mem_5_corrupt       (auto_bus_xing_in_a_mem_5_corrupt),
    .auto_in_a_mem_6_opcode        (auto_bus_xing_in_a_mem_6_opcode),
    .auto_in_a_mem_6_param         (auto_bus_xing_in_a_mem_6_param),
    .auto_in_a_mem_6_size          (auto_bus_xing_in_a_mem_6_size),
    .auto_in_a_mem_6_source        (auto_bus_xing_in_a_mem_6_source),
    .auto_in_a_mem_6_address       (auto_bus_xing_in_a_mem_6_address),
    .auto_in_a_mem_6_mask          (auto_bus_xing_in_a_mem_6_mask),
    .auto_in_a_mem_6_data          (auto_bus_xing_in_a_mem_6_data),
    .auto_in_a_mem_6_corrupt       (auto_bus_xing_in_a_mem_6_corrupt),
    .auto_in_a_mem_7_opcode        (auto_bus_xing_in_a_mem_7_opcode),
    .auto_in_a_mem_7_param         (auto_bus_xing_in_a_mem_7_param),
    .auto_in_a_mem_7_size          (auto_bus_xing_in_a_mem_7_size),
    .auto_in_a_mem_7_source        (auto_bus_xing_in_a_mem_7_source),
    .auto_in_a_mem_7_address       (auto_bus_xing_in_a_mem_7_address),
    .auto_in_a_mem_7_mask          (auto_bus_xing_in_a_mem_7_mask),
    .auto_in_a_mem_7_data          (auto_bus_xing_in_a_mem_7_data),
    .auto_in_a_mem_7_corrupt       (auto_bus_xing_in_a_mem_7_corrupt),
    .auto_in_a_ridx                (auto_bus_xing_in_a_ridx),
    .auto_in_a_widx                (auto_bus_xing_in_a_widx),
    .auto_in_a_safe_ridx_valid     (auto_bus_xing_in_a_safe_ridx_valid),
    .auto_in_a_safe_widx_valid     (auto_bus_xing_in_a_safe_widx_valid),
    .auto_in_a_safe_source_reset_n (auto_bus_xing_in_a_safe_source_reset_n),
    .auto_in_a_safe_sink_reset_n   (auto_bus_xing_in_a_safe_sink_reset_n),
    .auto_in_d_mem_0_opcode        (auto_bus_xing_in_d_mem_0_opcode),
    .auto_in_d_mem_0_param         (auto_bus_xing_in_d_mem_0_param),
    .auto_in_d_mem_0_size          (auto_bus_xing_in_d_mem_0_size),
    .auto_in_d_mem_0_source        (auto_bus_xing_in_d_mem_0_source),
    .auto_in_d_mem_0_sink          (auto_bus_xing_in_d_mem_0_sink),
    .auto_in_d_mem_0_denied        (auto_bus_xing_in_d_mem_0_denied),
    .auto_in_d_mem_0_data          (auto_bus_xing_in_d_mem_0_data),
    .auto_in_d_mem_0_corrupt       (auto_bus_xing_in_d_mem_0_corrupt),
    .auto_in_d_mem_1_opcode        (auto_bus_xing_in_d_mem_1_opcode),
    .auto_in_d_mem_1_param         (auto_bus_xing_in_d_mem_1_param),
    .auto_in_d_mem_1_size          (auto_bus_xing_in_d_mem_1_size),
    .auto_in_d_mem_1_source        (auto_bus_xing_in_d_mem_1_source),
    .auto_in_d_mem_1_sink          (auto_bus_xing_in_d_mem_1_sink),
    .auto_in_d_mem_1_denied        (auto_bus_xing_in_d_mem_1_denied),
    .auto_in_d_mem_1_data          (auto_bus_xing_in_d_mem_1_data),
    .auto_in_d_mem_1_corrupt       (auto_bus_xing_in_d_mem_1_corrupt),
    .auto_in_d_mem_2_opcode        (auto_bus_xing_in_d_mem_2_opcode),
    .auto_in_d_mem_2_param         (auto_bus_xing_in_d_mem_2_param),
    .auto_in_d_mem_2_size          (auto_bus_xing_in_d_mem_2_size),
    .auto_in_d_mem_2_source        (auto_bus_xing_in_d_mem_2_source),
    .auto_in_d_mem_2_sink          (auto_bus_xing_in_d_mem_2_sink),
    .auto_in_d_mem_2_denied        (auto_bus_xing_in_d_mem_2_denied),
    .auto_in_d_mem_2_data          (auto_bus_xing_in_d_mem_2_data),
    .auto_in_d_mem_2_corrupt       (auto_bus_xing_in_d_mem_2_corrupt),
    .auto_in_d_mem_3_opcode        (auto_bus_xing_in_d_mem_3_opcode),
    .auto_in_d_mem_3_param         (auto_bus_xing_in_d_mem_3_param),
    .auto_in_d_mem_3_size          (auto_bus_xing_in_d_mem_3_size),
    .auto_in_d_mem_3_source        (auto_bus_xing_in_d_mem_3_source),
    .auto_in_d_mem_3_sink          (auto_bus_xing_in_d_mem_3_sink),
    .auto_in_d_mem_3_denied        (auto_bus_xing_in_d_mem_3_denied),
    .auto_in_d_mem_3_data          (auto_bus_xing_in_d_mem_3_data),
    .auto_in_d_mem_3_corrupt       (auto_bus_xing_in_d_mem_3_corrupt),
    .auto_in_d_mem_4_opcode        (auto_bus_xing_in_d_mem_4_opcode),
    .auto_in_d_mem_4_param         (auto_bus_xing_in_d_mem_4_param),
    .auto_in_d_mem_4_size          (auto_bus_xing_in_d_mem_4_size),
    .auto_in_d_mem_4_source        (auto_bus_xing_in_d_mem_4_source),
    .auto_in_d_mem_4_sink          (auto_bus_xing_in_d_mem_4_sink),
    .auto_in_d_mem_4_denied        (auto_bus_xing_in_d_mem_4_denied),
    .auto_in_d_mem_4_data          (auto_bus_xing_in_d_mem_4_data),
    .auto_in_d_mem_4_corrupt       (auto_bus_xing_in_d_mem_4_corrupt),
    .auto_in_d_mem_5_opcode        (auto_bus_xing_in_d_mem_5_opcode),
    .auto_in_d_mem_5_param         (auto_bus_xing_in_d_mem_5_param),
    .auto_in_d_mem_5_size          (auto_bus_xing_in_d_mem_5_size),
    .auto_in_d_mem_5_source        (auto_bus_xing_in_d_mem_5_source),
    .auto_in_d_mem_5_sink          (auto_bus_xing_in_d_mem_5_sink),
    .auto_in_d_mem_5_denied        (auto_bus_xing_in_d_mem_5_denied),
    .auto_in_d_mem_5_data          (auto_bus_xing_in_d_mem_5_data),
    .auto_in_d_mem_5_corrupt       (auto_bus_xing_in_d_mem_5_corrupt),
    .auto_in_d_mem_6_opcode        (auto_bus_xing_in_d_mem_6_opcode),
    .auto_in_d_mem_6_param         (auto_bus_xing_in_d_mem_6_param),
    .auto_in_d_mem_6_size          (auto_bus_xing_in_d_mem_6_size),
    .auto_in_d_mem_6_source        (auto_bus_xing_in_d_mem_6_source),
    .auto_in_d_mem_6_sink          (auto_bus_xing_in_d_mem_6_sink),
    .auto_in_d_mem_6_denied        (auto_bus_xing_in_d_mem_6_denied),
    .auto_in_d_mem_6_data          (auto_bus_xing_in_d_mem_6_data),
    .auto_in_d_mem_6_corrupt       (auto_bus_xing_in_d_mem_6_corrupt),
    .auto_in_d_mem_7_opcode        (auto_bus_xing_in_d_mem_7_opcode),
    .auto_in_d_mem_7_param         (auto_bus_xing_in_d_mem_7_param),
    .auto_in_d_mem_7_size          (auto_bus_xing_in_d_mem_7_size),
    .auto_in_d_mem_7_source        (auto_bus_xing_in_d_mem_7_source),
    .auto_in_d_mem_7_sink          (auto_bus_xing_in_d_mem_7_sink),
    .auto_in_d_mem_7_denied        (auto_bus_xing_in_d_mem_7_denied),
    .auto_in_d_mem_7_data          (auto_bus_xing_in_d_mem_7_data),
    .auto_in_d_mem_7_corrupt       (auto_bus_xing_in_d_mem_7_corrupt),
    .auto_in_d_ridx                (auto_bus_xing_in_d_ridx),
    .auto_in_d_widx                (auto_bus_xing_in_d_widx),
    .auto_in_d_safe_ridx_valid     (auto_bus_xing_in_d_safe_ridx_valid),
    .auto_in_d_safe_widx_valid     (auto_bus_xing_in_d_safe_widx_valid),
    .auto_in_d_safe_source_reset_n (auto_bus_xing_in_d_safe_source_reset_n),
    .auto_in_d_safe_sink_reset_n   (auto_bus_xing_in_d_safe_sink_reset_n),
    .auto_out_a_ready              (_fixer_auto_in_a_ready),
    .auto_out_a_valid              (_asink_auto_out_a_valid),
    .auto_out_a_bits_opcode        (_asink_auto_out_a_bits_opcode),
    .auto_out_a_bits_param         (_asink_auto_out_a_bits_param),
    .auto_out_a_bits_size          (_asink_auto_out_a_bits_size),
    .auto_out_a_bits_source        (_asink_auto_out_a_bits_source),
    .auto_out_a_bits_address       (_asink_auto_out_a_bits_address),
    .auto_out_a_bits_mask          (_asink_auto_out_a_bits_mask),
    .auto_out_a_bits_data          (_asink_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt       (_asink_auto_out_a_bits_corrupt),
    .auto_out_d_ready              (_asink_auto_out_d_ready),
    .auto_out_d_valid              (_fixer_auto_in_d_valid),
    .auto_out_d_bits_opcode        (_fixer_auto_in_d_bits_opcode),
    .auto_out_d_bits_param         (_fixer_auto_in_d_bits_param),
    .auto_out_d_bits_size          (_fixer_auto_in_d_bits_size),
    .auto_out_d_bits_source        (_fixer_auto_in_d_bits_source),
    .auto_out_d_bits_sink          (_fixer_auto_in_d_bits_sink),
    .auto_out_d_bits_denied        (_fixer_auto_in_d_bits_denied),
    .auto_out_d_bits_data          (_fixer_auto_in_d_bits_data),
    .auto_out_d_bits_corrupt       (_fixer_auto_in_d_bits_corrupt)
  );
  assign auto_subsystem_mbus_clock_groups_out_member_subsystem_obus_0_clock = auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_1_clock;
  assign auto_subsystem_mbus_clock_groups_out_member_subsystem_obus_0_reset = auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_1_reset;
endmodule

