// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLAsyncCrossingSink_1(
  input         clock,
                reset,
  input  [2:0]  auto_in_a_mem_0_opcode,
                auto_in_a_mem_0_param,
  input  [3:0]  auto_in_a_mem_0_size,
  input  [4:0]  auto_in_a_mem_0_source,
  input  [32:0] auto_in_a_mem_0_address,
  input  [7:0]  auto_in_a_mem_0_mask,
  input  [63:0] auto_in_a_mem_0_data,
  input         auto_in_a_mem_0_corrupt,
  input  [2:0]  auto_in_a_mem_1_opcode,
                auto_in_a_mem_1_param,
  input  [3:0]  auto_in_a_mem_1_size,
  input  [4:0]  auto_in_a_mem_1_source,
  input  [32:0] auto_in_a_mem_1_address,
  input  [7:0]  auto_in_a_mem_1_mask,
  input  [63:0] auto_in_a_mem_1_data,
  input         auto_in_a_mem_1_corrupt,
  input  [2:0]  auto_in_a_mem_2_opcode,
                auto_in_a_mem_2_param,
  input  [3:0]  auto_in_a_mem_2_size,
  input  [4:0]  auto_in_a_mem_2_source,
  input  [32:0] auto_in_a_mem_2_address,
  input  [7:0]  auto_in_a_mem_2_mask,
  input  [63:0] auto_in_a_mem_2_data,
  input         auto_in_a_mem_2_corrupt,
  input  [2:0]  auto_in_a_mem_3_opcode,
                auto_in_a_mem_3_param,
  input  [3:0]  auto_in_a_mem_3_size,
  input  [4:0]  auto_in_a_mem_3_source,
  input  [32:0] auto_in_a_mem_3_address,
  input  [7:0]  auto_in_a_mem_3_mask,
  input  [63:0] auto_in_a_mem_3_data,
  input         auto_in_a_mem_3_corrupt,
  input  [2:0]  auto_in_a_mem_4_opcode,
                auto_in_a_mem_4_param,
  input  [3:0]  auto_in_a_mem_4_size,
  input  [4:0]  auto_in_a_mem_4_source,
  input  [32:0] auto_in_a_mem_4_address,
  input  [7:0]  auto_in_a_mem_4_mask,
  input  [63:0] auto_in_a_mem_4_data,
  input         auto_in_a_mem_4_corrupt,
  input  [2:0]  auto_in_a_mem_5_opcode,
                auto_in_a_mem_5_param,
  input  [3:0]  auto_in_a_mem_5_size,
  input  [4:0]  auto_in_a_mem_5_source,
  input  [32:0] auto_in_a_mem_5_address,
  input  [7:0]  auto_in_a_mem_5_mask,
  input  [63:0] auto_in_a_mem_5_data,
  input         auto_in_a_mem_5_corrupt,
  input  [2:0]  auto_in_a_mem_6_opcode,
                auto_in_a_mem_6_param,
  input  [3:0]  auto_in_a_mem_6_size,
  input  [4:0]  auto_in_a_mem_6_source,
  input  [32:0] auto_in_a_mem_6_address,
  input  [7:0]  auto_in_a_mem_6_mask,
  input  [63:0] auto_in_a_mem_6_data,
  input         auto_in_a_mem_6_corrupt,
  input  [2:0]  auto_in_a_mem_7_opcode,
                auto_in_a_mem_7_param,
  input  [3:0]  auto_in_a_mem_7_size,
  input  [4:0]  auto_in_a_mem_7_source,
  input  [32:0] auto_in_a_mem_7_address,
  input  [7:0]  auto_in_a_mem_7_mask,
  input  [63:0] auto_in_a_mem_7_data,
  input         auto_in_a_mem_7_corrupt,
  output [3:0]  auto_in_a_ridx,
  input  [3:0]  auto_in_a_widx,
  output        auto_in_a_safe_ridx_valid,
  input         auto_in_a_safe_widx_valid,
                auto_in_a_safe_source_reset_n,
  output        auto_in_a_safe_sink_reset_n,
  output [1:0]  auto_in_b_mem_0_param,
  output [4:0]  auto_in_b_mem_0_source,
  output [32:0] auto_in_b_mem_0_address,
  output [1:0]  auto_in_b_mem_1_param,
  output [4:0]  auto_in_b_mem_1_source,
  output [32:0] auto_in_b_mem_1_address,
  output [1:0]  auto_in_b_mem_2_param,
  output [4:0]  auto_in_b_mem_2_source,
  output [32:0] auto_in_b_mem_2_address,
  output [1:0]  auto_in_b_mem_3_param,
  output [4:0]  auto_in_b_mem_3_source,
  output [32:0] auto_in_b_mem_3_address,
  output [1:0]  auto_in_b_mem_4_param,
  output [4:0]  auto_in_b_mem_4_source,
  output [32:0] auto_in_b_mem_4_address,
  output [1:0]  auto_in_b_mem_5_param,
  output [4:0]  auto_in_b_mem_5_source,
  output [32:0] auto_in_b_mem_5_address,
  output [1:0]  auto_in_b_mem_6_param,
  output [4:0]  auto_in_b_mem_6_source,
  output [32:0] auto_in_b_mem_6_address,
  output [1:0]  auto_in_b_mem_7_param,
  output [4:0]  auto_in_b_mem_7_source,
  output [32:0] auto_in_b_mem_7_address,
  input  [3:0]  auto_in_b_ridx,
  output [3:0]  auto_in_b_widx,
  input         auto_in_b_safe_ridx_valid,
  output        auto_in_b_safe_widx_valid,
                auto_in_b_safe_source_reset_n,
  input         auto_in_b_safe_sink_reset_n,
  input  [2:0]  auto_in_c_mem_0_opcode,
                auto_in_c_mem_0_param,
  input  [3:0]  auto_in_c_mem_0_size,
  input  [4:0]  auto_in_c_mem_0_source,
  input  [32:0] auto_in_c_mem_0_address,
  input  [63:0] auto_in_c_mem_0_data,
  input         auto_in_c_mem_0_corrupt,
  input  [2:0]  auto_in_c_mem_1_opcode,
                auto_in_c_mem_1_param,
  input  [3:0]  auto_in_c_mem_1_size,
  input  [4:0]  auto_in_c_mem_1_source,
  input  [32:0] auto_in_c_mem_1_address,
  input  [63:0] auto_in_c_mem_1_data,
  input         auto_in_c_mem_1_corrupt,
  input  [2:0]  auto_in_c_mem_2_opcode,
                auto_in_c_mem_2_param,
  input  [3:0]  auto_in_c_mem_2_size,
  input  [4:0]  auto_in_c_mem_2_source,
  input  [32:0] auto_in_c_mem_2_address,
  input  [63:0] auto_in_c_mem_2_data,
  input         auto_in_c_mem_2_corrupt,
  input  [2:0]  auto_in_c_mem_3_opcode,
                auto_in_c_mem_3_param,
  input  [3:0]  auto_in_c_mem_3_size,
  input  [4:0]  auto_in_c_mem_3_source,
  input  [32:0] auto_in_c_mem_3_address,
  input  [63:0] auto_in_c_mem_3_data,
  input         auto_in_c_mem_3_corrupt,
  input  [2:0]  auto_in_c_mem_4_opcode,
                auto_in_c_mem_4_param,
  input  [3:0]  auto_in_c_mem_4_size,
  input  [4:0]  auto_in_c_mem_4_source,
  input  [32:0] auto_in_c_mem_4_address,
  input  [63:0] auto_in_c_mem_4_data,
  input         auto_in_c_mem_4_corrupt,
  input  [2:0]  auto_in_c_mem_5_opcode,
                auto_in_c_mem_5_param,
  input  [3:0]  auto_in_c_mem_5_size,
  input  [4:0]  auto_in_c_mem_5_source,
  input  [32:0] auto_in_c_mem_5_address,
  input  [63:0] auto_in_c_mem_5_data,
  input         auto_in_c_mem_5_corrupt,
  input  [2:0]  auto_in_c_mem_6_opcode,
                auto_in_c_mem_6_param,
  input  [3:0]  auto_in_c_mem_6_size,
  input  [4:0]  auto_in_c_mem_6_source,
  input  [32:0] auto_in_c_mem_6_address,
  input  [63:0] auto_in_c_mem_6_data,
  input         auto_in_c_mem_6_corrupt,
  input  [2:0]  auto_in_c_mem_7_opcode,
                auto_in_c_mem_7_param,
  input  [3:0]  auto_in_c_mem_7_size,
  input  [4:0]  auto_in_c_mem_7_source,
  input  [32:0] auto_in_c_mem_7_address,
  input  [63:0] auto_in_c_mem_7_data,
  input         auto_in_c_mem_7_corrupt,
  output [3:0]  auto_in_c_ridx,
  input  [3:0]  auto_in_c_widx,
  output        auto_in_c_safe_ridx_valid,
  input         auto_in_c_safe_widx_valid,
                auto_in_c_safe_source_reset_n,
  output        auto_in_c_safe_sink_reset_n,
  output [2:0]  auto_in_d_mem_0_opcode,
  output [1:0]  auto_in_d_mem_0_param,
  output [3:0]  auto_in_d_mem_0_size,
  output [4:0]  auto_in_d_mem_0_source,
  output [2:0]  auto_in_d_mem_0_sink,
  output        auto_in_d_mem_0_denied,
  output [63:0] auto_in_d_mem_0_data,
  output        auto_in_d_mem_0_corrupt,
  output [2:0]  auto_in_d_mem_1_opcode,
  output [1:0]  auto_in_d_mem_1_param,
  output [3:0]  auto_in_d_mem_1_size,
  output [4:0]  auto_in_d_mem_1_source,
  output [2:0]  auto_in_d_mem_1_sink,
  output        auto_in_d_mem_1_denied,
  output [63:0] auto_in_d_mem_1_data,
  output        auto_in_d_mem_1_corrupt,
  output [2:0]  auto_in_d_mem_2_opcode,
  output [1:0]  auto_in_d_mem_2_param,
  output [3:0]  auto_in_d_mem_2_size,
  output [4:0]  auto_in_d_mem_2_source,
  output [2:0]  auto_in_d_mem_2_sink,
  output        auto_in_d_mem_2_denied,
  output [63:0] auto_in_d_mem_2_data,
  output        auto_in_d_mem_2_corrupt,
  output [2:0]  auto_in_d_mem_3_opcode,
  output [1:0]  auto_in_d_mem_3_param,
  output [3:0]  auto_in_d_mem_3_size,
  output [4:0]  auto_in_d_mem_3_source,
  output [2:0]  auto_in_d_mem_3_sink,
  output        auto_in_d_mem_3_denied,
  output [63:0] auto_in_d_mem_3_data,
  output        auto_in_d_mem_3_corrupt,
  output [2:0]  auto_in_d_mem_4_opcode,
  output [1:0]  auto_in_d_mem_4_param,
  output [3:0]  auto_in_d_mem_4_size,
  output [4:0]  auto_in_d_mem_4_source,
  output [2:0]  auto_in_d_mem_4_sink,
  output        auto_in_d_mem_4_denied,
  output [63:0] auto_in_d_mem_4_data,
  output        auto_in_d_mem_4_corrupt,
  output [2:0]  auto_in_d_mem_5_opcode,
  output [1:0]  auto_in_d_mem_5_param,
  output [3:0]  auto_in_d_mem_5_size,
  output [4:0]  auto_in_d_mem_5_source,
  output [2:0]  auto_in_d_mem_5_sink,
  output        auto_in_d_mem_5_denied,
  output [63:0] auto_in_d_mem_5_data,
  output        auto_in_d_mem_5_corrupt,
  output [2:0]  auto_in_d_mem_6_opcode,
  output [1:0]  auto_in_d_mem_6_param,
  output [3:0]  auto_in_d_mem_6_size,
  output [4:0]  auto_in_d_mem_6_source,
  output [2:0]  auto_in_d_mem_6_sink,
  output        auto_in_d_mem_6_denied,
  output [63:0] auto_in_d_mem_6_data,
  output        auto_in_d_mem_6_corrupt,
  output [2:0]  auto_in_d_mem_7_opcode,
  output [1:0]  auto_in_d_mem_7_param,
  output [3:0]  auto_in_d_mem_7_size,
  output [4:0]  auto_in_d_mem_7_source,
  output [2:0]  auto_in_d_mem_7_sink,
  output        auto_in_d_mem_7_denied,
  output [63:0] auto_in_d_mem_7_data,
  output        auto_in_d_mem_7_corrupt,
  input  [3:0]  auto_in_d_ridx,
  output [3:0]  auto_in_d_widx,
  input         auto_in_d_safe_ridx_valid,
  output        auto_in_d_safe_widx_valid,
                auto_in_d_safe_source_reset_n,
  input         auto_in_d_safe_sink_reset_n,
  input  [2:0]  auto_in_e_mem_0_sink,
                auto_in_e_mem_1_sink,
                auto_in_e_mem_2_sink,
                auto_in_e_mem_3_sink,
                auto_in_e_mem_4_sink,
                auto_in_e_mem_5_sink,
                auto_in_e_mem_6_sink,
                auto_in_e_mem_7_sink,
  output [3:0]  auto_in_e_ridx,
  input  [3:0]  auto_in_e_widx,
  output        auto_in_e_safe_ridx_valid,
  input         auto_in_e_safe_widx_valid,
                auto_in_e_safe_source_reset_n,
  output        auto_in_e_safe_sink_reset_n,
  input         auto_out_a_ready,
  output        auto_out_a_valid,
  output [2:0]  auto_out_a_bits_opcode,
                auto_out_a_bits_param,
  output [3:0]  auto_out_a_bits_size,
  output [4:0]  auto_out_a_bits_source,
  output [32:0] auto_out_a_bits_address,
  output [7:0]  auto_out_a_bits_mask,
  output [63:0] auto_out_a_bits_data,
  output        auto_out_a_bits_corrupt,
                auto_out_b_ready,
  input         auto_out_b_valid,
  input  [1:0]  auto_out_b_bits_param,
  input  [4:0]  auto_out_b_bits_source,
  input  [32:0] auto_out_b_bits_address,
  input         auto_out_c_ready,
  output        auto_out_c_valid,
  output [2:0]  auto_out_c_bits_opcode,
                auto_out_c_bits_param,
  output [3:0]  auto_out_c_bits_size,
  output [4:0]  auto_out_c_bits_source,
  output [32:0] auto_out_c_bits_address,
  output [63:0] auto_out_c_bits_data,
  output        auto_out_c_bits_corrupt,
                auto_out_d_ready,
  input         auto_out_d_valid,
  input  [2:0]  auto_out_d_bits_opcode,
  input  [1:0]  auto_out_d_bits_param,
  input  [3:0]  auto_out_d_bits_size,
  input  [4:0]  auto_out_d_bits_source,
  input  [2:0]  auto_out_d_bits_sink,
  input         auto_out_d_bits_denied,
  input  [63:0] auto_out_d_bits_data,
  input         auto_out_d_bits_corrupt,
                auto_out_e_ready,
  output        auto_out_e_valid,
  output [2:0]  auto_out_e_bits_sink
);

  AsyncQueueSink_2 nodeOut_a_sink (
    .clock                        (clock),
    .reset                        (reset),
    .io_deq_ready                 (auto_out_a_ready),
    .io_deq_valid                 (auto_out_a_valid),
    .io_deq_bits_opcode           (auto_out_a_bits_opcode),
    .io_deq_bits_param            (auto_out_a_bits_param),
    .io_deq_bits_size             (auto_out_a_bits_size),
    .io_deq_bits_source           (auto_out_a_bits_source),
    .io_deq_bits_address          (auto_out_a_bits_address),
    .io_deq_bits_mask             (auto_out_a_bits_mask),
    .io_deq_bits_data             (auto_out_a_bits_data),
    .io_deq_bits_corrupt          (auto_out_a_bits_corrupt),
    .io_async_mem_0_opcode        (auto_in_a_mem_0_opcode),
    .io_async_mem_0_param         (auto_in_a_mem_0_param),
    .io_async_mem_0_size          (auto_in_a_mem_0_size),
    .io_async_mem_0_source        (auto_in_a_mem_0_source),
    .io_async_mem_0_address       (auto_in_a_mem_0_address),
    .io_async_mem_0_mask          (auto_in_a_mem_0_mask),
    .io_async_mem_0_data          (auto_in_a_mem_0_data),
    .io_async_mem_0_corrupt       (auto_in_a_mem_0_corrupt),
    .io_async_mem_1_opcode        (auto_in_a_mem_1_opcode),
    .io_async_mem_1_param         (auto_in_a_mem_1_param),
    .io_async_mem_1_size          (auto_in_a_mem_1_size),
    .io_async_mem_1_source        (auto_in_a_mem_1_source),
    .io_async_mem_1_address       (auto_in_a_mem_1_address),
    .io_async_mem_1_mask          (auto_in_a_mem_1_mask),
    .io_async_mem_1_data          (auto_in_a_mem_1_data),
    .io_async_mem_1_corrupt       (auto_in_a_mem_1_corrupt),
    .io_async_mem_2_opcode        (auto_in_a_mem_2_opcode),
    .io_async_mem_2_param         (auto_in_a_mem_2_param),
    .io_async_mem_2_size          (auto_in_a_mem_2_size),
    .io_async_mem_2_source        (auto_in_a_mem_2_source),
    .io_async_mem_2_address       (auto_in_a_mem_2_address),
    .io_async_mem_2_mask          (auto_in_a_mem_2_mask),
    .io_async_mem_2_data          (auto_in_a_mem_2_data),
    .io_async_mem_2_corrupt       (auto_in_a_mem_2_corrupt),
    .io_async_mem_3_opcode        (auto_in_a_mem_3_opcode),
    .io_async_mem_3_param         (auto_in_a_mem_3_param),
    .io_async_mem_3_size          (auto_in_a_mem_3_size),
    .io_async_mem_3_source        (auto_in_a_mem_3_source),
    .io_async_mem_3_address       (auto_in_a_mem_3_address),
    .io_async_mem_3_mask          (auto_in_a_mem_3_mask),
    .io_async_mem_3_data          (auto_in_a_mem_3_data),
    .io_async_mem_3_corrupt       (auto_in_a_mem_3_corrupt),
    .io_async_mem_4_opcode        (auto_in_a_mem_4_opcode),
    .io_async_mem_4_param         (auto_in_a_mem_4_param),
    .io_async_mem_4_size          (auto_in_a_mem_4_size),
    .io_async_mem_4_source        (auto_in_a_mem_4_source),
    .io_async_mem_4_address       (auto_in_a_mem_4_address),
    .io_async_mem_4_mask          (auto_in_a_mem_4_mask),
    .io_async_mem_4_data          (auto_in_a_mem_4_data),
    .io_async_mem_4_corrupt       (auto_in_a_mem_4_corrupt),
    .io_async_mem_5_opcode        (auto_in_a_mem_5_opcode),
    .io_async_mem_5_param         (auto_in_a_mem_5_param),
    .io_async_mem_5_size          (auto_in_a_mem_5_size),
    .io_async_mem_5_source        (auto_in_a_mem_5_source),
    .io_async_mem_5_address       (auto_in_a_mem_5_address),
    .io_async_mem_5_mask          (auto_in_a_mem_5_mask),
    .io_async_mem_5_data          (auto_in_a_mem_5_data),
    .io_async_mem_5_corrupt       (auto_in_a_mem_5_corrupt),
    .io_async_mem_6_opcode        (auto_in_a_mem_6_opcode),
    .io_async_mem_6_param         (auto_in_a_mem_6_param),
    .io_async_mem_6_size          (auto_in_a_mem_6_size),
    .io_async_mem_6_source        (auto_in_a_mem_6_source),
    .io_async_mem_6_address       (auto_in_a_mem_6_address),
    .io_async_mem_6_mask          (auto_in_a_mem_6_mask),
    .io_async_mem_6_data          (auto_in_a_mem_6_data),
    .io_async_mem_6_corrupt       (auto_in_a_mem_6_corrupt),
    .io_async_mem_7_opcode        (auto_in_a_mem_7_opcode),
    .io_async_mem_7_param         (auto_in_a_mem_7_param),
    .io_async_mem_7_size          (auto_in_a_mem_7_size),
    .io_async_mem_7_source        (auto_in_a_mem_7_source),
    .io_async_mem_7_address       (auto_in_a_mem_7_address),
    .io_async_mem_7_mask          (auto_in_a_mem_7_mask),
    .io_async_mem_7_data          (auto_in_a_mem_7_data),
    .io_async_mem_7_corrupt       (auto_in_a_mem_7_corrupt),
    .io_async_ridx                (auto_in_a_ridx),
    .io_async_widx                (auto_in_a_widx),
    .io_async_safe_ridx_valid     (auto_in_a_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_a_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_a_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_a_safe_sink_reset_n)
  );
  AsyncQueueSource_2 nodeIn_d_source (
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (auto_out_d_ready),
    .io_enq_valid                 (auto_out_d_valid),
    .io_enq_bits_opcode           (auto_out_d_bits_opcode),
    .io_enq_bits_param            (auto_out_d_bits_param),
    .io_enq_bits_size             (auto_out_d_bits_size),
    .io_enq_bits_source           (auto_out_d_bits_source),
    .io_enq_bits_sink             (auto_out_d_bits_sink),
    .io_enq_bits_denied           (auto_out_d_bits_denied),
    .io_enq_bits_data             (auto_out_d_bits_data),
    .io_enq_bits_corrupt          (auto_out_d_bits_corrupt),
    .io_async_mem_0_opcode        (auto_in_d_mem_0_opcode),
    .io_async_mem_0_param         (auto_in_d_mem_0_param),
    .io_async_mem_0_size          (auto_in_d_mem_0_size),
    .io_async_mem_0_source        (auto_in_d_mem_0_source),
    .io_async_mem_0_sink          (auto_in_d_mem_0_sink),
    .io_async_mem_0_denied        (auto_in_d_mem_0_denied),
    .io_async_mem_0_data          (auto_in_d_mem_0_data),
    .io_async_mem_0_corrupt       (auto_in_d_mem_0_corrupt),
    .io_async_mem_1_opcode        (auto_in_d_mem_1_opcode),
    .io_async_mem_1_param         (auto_in_d_mem_1_param),
    .io_async_mem_1_size          (auto_in_d_mem_1_size),
    .io_async_mem_1_source        (auto_in_d_mem_1_source),
    .io_async_mem_1_sink          (auto_in_d_mem_1_sink),
    .io_async_mem_1_denied        (auto_in_d_mem_1_denied),
    .io_async_mem_1_data          (auto_in_d_mem_1_data),
    .io_async_mem_1_corrupt       (auto_in_d_mem_1_corrupt),
    .io_async_mem_2_opcode        (auto_in_d_mem_2_opcode),
    .io_async_mem_2_param         (auto_in_d_mem_2_param),
    .io_async_mem_2_size          (auto_in_d_mem_2_size),
    .io_async_mem_2_source        (auto_in_d_mem_2_source),
    .io_async_mem_2_sink          (auto_in_d_mem_2_sink),
    .io_async_mem_2_denied        (auto_in_d_mem_2_denied),
    .io_async_mem_2_data          (auto_in_d_mem_2_data),
    .io_async_mem_2_corrupt       (auto_in_d_mem_2_corrupt),
    .io_async_mem_3_opcode        (auto_in_d_mem_3_opcode),
    .io_async_mem_3_param         (auto_in_d_mem_3_param),
    .io_async_mem_3_size          (auto_in_d_mem_3_size),
    .io_async_mem_3_source        (auto_in_d_mem_3_source),
    .io_async_mem_3_sink          (auto_in_d_mem_3_sink),
    .io_async_mem_3_denied        (auto_in_d_mem_3_denied),
    .io_async_mem_3_data          (auto_in_d_mem_3_data),
    .io_async_mem_3_corrupt       (auto_in_d_mem_3_corrupt),
    .io_async_mem_4_opcode        (auto_in_d_mem_4_opcode),
    .io_async_mem_4_param         (auto_in_d_mem_4_param),
    .io_async_mem_4_size          (auto_in_d_mem_4_size),
    .io_async_mem_4_source        (auto_in_d_mem_4_source),
    .io_async_mem_4_sink          (auto_in_d_mem_4_sink),
    .io_async_mem_4_denied        (auto_in_d_mem_4_denied),
    .io_async_mem_4_data          (auto_in_d_mem_4_data),
    .io_async_mem_4_corrupt       (auto_in_d_mem_4_corrupt),
    .io_async_mem_5_opcode        (auto_in_d_mem_5_opcode),
    .io_async_mem_5_param         (auto_in_d_mem_5_param),
    .io_async_mem_5_size          (auto_in_d_mem_5_size),
    .io_async_mem_5_source        (auto_in_d_mem_5_source),
    .io_async_mem_5_sink          (auto_in_d_mem_5_sink),
    .io_async_mem_5_denied        (auto_in_d_mem_5_denied),
    .io_async_mem_5_data          (auto_in_d_mem_5_data),
    .io_async_mem_5_corrupt       (auto_in_d_mem_5_corrupt),
    .io_async_mem_6_opcode        (auto_in_d_mem_6_opcode),
    .io_async_mem_6_param         (auto_in_d_mem_6_param),
    .io_async_mem_6_size          (auto_in_d_mem_6_size),
    .io_async_mem_6_source        (auto_in_d_mem_6_source),
    .io_async_mem_6_sink          (auto_in_d_mem_6_sink),
    .io_async_mem_6_denied        (auto_in_d_mem_6_denied),
    .io_async_mem_6_data          (auto_in_d_mem_6_data),
    .io_async_mem_6_corrupt       (auto_in_d_mem_6_corrupt),
    .io_async_mem_7_opcode        (auto_in_d_mem_7_opcode),
    .io_async_mem_7_param         (auto_in_d_mem_7_param),
    .io_async_mem_7_size          (auto_in_d_mem_7_size),
    .io_async_mem_7_source        (auto_in_d_mem_7_source),
    .io_async_mem_7_sink          (auto_in_d_mem_7_sink),
    .io_async_mem_7_denied        (auto_in_d_mem_7_denied),
    .io_async_mem_7_data          (auto_in_d_mem_7_data),
    .io_async_mem_7_corrupt       (auto_in_d_mem_7_corrupt),
    .io_async_ridx                (auto_in_d_ridx),
    .io_async_widx                (auto_in_d_widx),
    .io_async_safe_ridx_valid     (auto_in_d_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_d_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_d_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_d_safe_sink_reset_n)
  );
  AsyncQueueSource_3 nodeIn_b_source (
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (auto_out_b_ready),
    .io_enq_valid                 (auto_out_b_valid),
    .io_enq_bits_param            (auto_out_b_bits_param),
    .io_enq_bits_source           (auto_out_b_bits_source),
    .io_enq_bits_address          (auto_out_b_bits_address),
    .io_async_mem_0_param         (auto_in_b_mem_0_param),
    .io_async_mem_0_source        (auto_in_b_mem_0_source),
    .io_async_mem_0_address       (auto_in_b_mem_0_address),
    .io_async_mem_1_param         (auto_in_b_mem_1_param),
    .io_async_mem_1_source        (auto_in_b_mem_1_source),
    .io_async_mem_1_address       (auto_in_b_mem_1_address),
    .io_async_mem_2_param         (auto_in_b_mem_2_param),
    .io_async_mem_2_source        (auto_in_b_mem_2_source),
    .io_async_mem_2_address       (auto_in_b_mem_2_address),
    .io_async_mem_3_param         (auto_in_b_mem_3_param),
    .io_async_mem_3_source        (auto_in_b_mem_3_source),
    .io_async_mem_3_address       (auto_in_b_mem_3_address),
    .io_async_mem_4_param         (auto_in_b_mem_4_param),
    .io_async_mem_4_source        (auto_in_b_mem_4_source),
    .io_async_mem_4_address       (auto_in_b_mem_4_address),
    .io_async_mem_5_param         (auto_in_b_mem_5_param),
    .io_async_mem_5_source        (auto_in_b_mem_5_source),
    .io_async_mem_5_address       (auto_in_b_mem_5_address),
    .io_async_mem_6_param         (auto_in_b_mem_6_param),
    .io_async_mem_6_source        (auto_in_b_mem_6_source),
    .io_async_mem_6_address       (auto_in_b_mem_6_address),
    .io_async_mem_7_param         (auto_in_b_mem_7_param),
    .io_async_mem_7_source        (auto_in_b_mem_7_source),
    .io_async_mem_7_address       (auto_in_b_mem_7_address),
    .io_async_ridx                (auto_in_b_ridx),
    .io_async_widx                (auto_in_b_widx),
    .io_async_safe_ridx_valid     (auto_in_b_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_b_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_b_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_b_safe_sink_reset_n)
  );
  AsyncQueueSink_3 nodeOut_c_sink (
    .clock                        (clock),
    .reset                        (reset),
    .io_deq_ready                 (auto_out_c_ready),
    .io_deq_valid                 (auto_out_c_valid),
    .io_deq_bits_opcode           (auto_out_c_bits_opcode),
    .io_deq_bits_param            (auto_out_c_bits_param),
    .io_deq_bits_size             (auto_out_c_bits_size),
    .io_deq_bits_source           (auto_out_c_bits_source),
    .io_deq_bits_address          (auto_out_c_bits_address),
    .io_deq_bits_data             (auto_out_c_bits_data),
    .io_deq_bits_corrupt          (auto_out_c_bits_corrupt),
    .io_async_mem_0_opcode        (auto_in_c_mem_0_opcode),
    .io_async_mem_0_param         (auto_in_c_mem_0_param),
    .io_async_mem_0_size          (auto_in_c_mem_0_size),
    .io_async_mem_0_source        (auto_in_c_mem_0_source),
    .io_async_mem_0_address       (auto_in_c_mem_0_address),
    .io_async_mem_0_data          (auto_in_c_mem_0_data),
    .io_async_mem_0_corrupt       (auto_in_c_mem_0_corrupt),
    .io_async_mem_1_opcode        (auto_in_c_mem_1_opcode),
    .io_async_mem_1_param         (auto_in_c_mem_1_param),
    .io_async_mem_1_size          (auto_in_c_mem_1_size),
    .io_async_mem_1_source        (auto_in_c_mem_1_source),
    .io_async_mem_1_address       (auto_in_c_mem_1_address),
    .io_async_mem_1_data          (auto_in_c_mem_1_data),
    .io_async_mem_1_corrupt       (auto_in_c_mem_1_corrupt),
    .io_async_mem_2_opcode        (auto_in_c_mem_2_opcode),
    .io_async_mem_2_param         (auto_in_c_mem_2_param),
    .io_async_mem_2_size          (auto_in_c_mem_2_size),
    .io_async_mem_2_source        (auto_in_c_mem_2_source),
    .io_async_mem_2_address       (auto_in_c_mem_2_address),
    .io_async_mem_2_data          (auto_in_c_mem_2_data),
    .io_async_mem_2_corrupt       (auto_in_c_mem_2_corrupt),
    .io_async_mem_3_opcode        (auto_in_c_mem_3_opcode),
    .io_async_mem_3_param         (auto_in_c_mem_3_param),
    .io_async_mem_3_size          (auto_in_c_mem_3_size),
    .io_async_mem_3_source        (auto_in_c_mem_3_source),
    .io_async_mem_3_address       (auto_in_c_mem_3_address),
    .io_async_mem_3_data          (auto_in_c_mem_3_data),
    .io_async_mem_3_corrupt       (auto_in_c_mem_3_corrupt),
    .io_async_mem_4_opcode        (auto_in_c_mem_4_opcode),
    .io_async_mem_4_param         (auto_in_c_mem_4_param),
    .io_async_mem_4_size          (auto_in_c_mem_4_size),
    .io_async_mem_4_source        (auto_in_c_mem_4_source),
    .io_async_mem_4_address       (auto_in_c_mem_4_address),
    .io_async_mem_4_data          (auto_in_c_mem_4_data),
    .io_async_mem_4_corrupt       (auto_in_c_mem_4_corrupt),
    .io_async_mem_5_opcode        (auto_in_c_mem_5_opcode),
    .io_async_mem_5_param         (auto_in_c_mem_5_param),
    .io_async_mem_5_size          (auto_in_c_mem_5_size),
    .io_async_mem_5_source        (auto_in_c_mem_5_source),
    .io_async_mem_5_address       (auto_in_c_mem_5_address),
    .io_async_mem_5_data          (auto_in_c_mem_5_data),
    .io_async_mem_5_corrupt       (auto_in_c_mem_5_corrupt),
    .io_async_mem_6_opcode        (auto_in_c_mem_6_opcode),
    .io_async_mem_6_param         (auto_in_c_mem_6_param),
    .io_async_mem_6_size          (auto_in_c_mem_6_size),
    .io_async_mem_6_source        (auto_in_c_mem_6_source),
    .io_async_mem_6_address       (auto_in_c_mem_6_address),
    .io_async_mem_6_data          (auto_in_c_mem_6_data),
    .io_async_mem_6_corrupt       (auto_in_c_mem_6_corrupt),
    .io_async_mem_7_opcode        (auto_in_c_mem_7_opcode),
    .io_async_mem_7_param         (auto_in_c_mem_7_param),
    .io_async_mem_7_size          (auto_in_c_mem_7_size),
    .io_async_mem_7_source        (auto_in_c_mem_7_source),
    .io_async_mem_7_address       (auto_in_c_mem_7_address),
    .io_async_mem_7_data          (auto_in_c_mem_7_data),
    .io_async_mem_7_corrupt       (auto_in_c_mem_7_corrupt),
    .io_async_ridx                (auto_in_c_ridx),
    .io_async_widx                (auto_in_c_widx),
    .io_async_safe_ridx_valid     (auto_in_c_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_c_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_c_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_c_safe_sink_reset_n)
  );
  AsyncQueueSink_4 nodeOut_e_sink (
    .clock                        (clock),
    .reset                        (reset),
    .io_deq_ready                 (auto_out_e_ready),
    .io_deq_valid                 (auto_out_e_valid),
    .io_deq_bits_sink             (auto_out_e_bits_sink),
    .io_async_mem_0_sink          (auto_in_e_mem_0_sink),
    .io_async_mem_1_sink          (auto_in_e_mem_1_sink),
    .io_async_mem_2_sink          (auto_in_e_mem_2_sink),
    .io_async_mem_3_sink          (auto_in_e_mem_3_sink),
    .io_async_mem_4_sink          (auto_in_e_mem_4_sink),
    .io_async_mem_5_sink          (auto_in_e_mem_5_sink),
    .io_async_mem_6_sink          (auto_in_e_mem_6_sink),
    .io_async_mem_7_sink          (auto_in_e_mem_7_sink),
    .io_async_ridx                (auto_in_e_ridx),
    .io_async_widx                (auto_in_e_widx),
    .io_async_safe_ridx_valid     (auto_in_e_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_in_e_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_in_e_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_in_e_safe_sink_reset_n)
  );
endmodule

