#!/usr/bin/env python3

# Find this path:
#
# /home/user/.cache/bazel/_bazel_user/7e6ad621f3f951c3ee6f5b179289b54e/execroot/_main/bazel-out/k8-fastbuild/bin/
#
# Where:
# _bazel_user is a folder where "user" is the username
# 7e6ad621f3f951c3ee6f5b179289b54e is the MD5 hash of the path name of workspace root
#     (as described in https://bazel.build/remote/output-directories#layout)
#
# Then print out the path

import os
import sys
import re
import argparse
import hashlib
from pathlib import Path
from glob import glob

PROJECT_DIR = Path(__file__).parent.resolve()


def find_path():
    path = os.path.expanduser("~/.cache/bazel/_bazel_" + os.getlogin())
    if not os.path.exists(path):
        print("Path does not exist: " + path)
        sys.exit(1)

    hash = hashlib.new("md5")
    hash.update(str(PROJECT_DIR).encode())
    d = hash.hexdigest()
    if re.match(r'[a-z0-9]{32}', d):
        path2 = os.path.join(path, d,
                             "execroot/_main/bazel-out/k8-fastbuild/bin")
        if os.path.exists(path2):
            return path2

    print("Could not find path")
    sys.exit(1)


def find_newest_log(path):
    files = glob(path + "/**/*.log", recursive=True)
    return max(files, key=os.path.getmtime, default=None)


if __name__ == "__main__":
    path = find_path()
    args = sys.argv[1:]
    parser = argparse.ArgumentParser()
    # add actions in argparser
    # print - default action
    # tail - print last 10 lines
    parser.add_argument("-t", "--tail", action="store_true")
    args = parser.parse_args(args)
    if args.tail:
        # scan recursively to find the most recent file ending in
        # .tmp.log:
        #
        # path + '/logs/asap7/DigitalTop/2_6_floorplan_pdn.tmp.log'
        tmpfile = find_newest_log(path + '/logs')
        if tmpfile is None:
            print("Could not find tmp file")
            sys.exit(1)
        print(tmpfile)
    else:
        print(path)
