name: MegaBoom

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Bazel files
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Download buildifier
        run: |
          wget https://github.com/bazelbuild/buildtools/releases/download/v6.4.0/buildifier-linux-amd64 -O /usr/local/bin/buildifier
          chmod +x /usr/local/bin/buildifier
          buildifier -version
      - name: Checkout megaboom
        uses: actions/checkout@v4
      - name: Check Bazel files
        run: |
          buildifier -lint warn -r .

  test-target-bazel:
    name: Bazel flow - test targets
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false
      - name: Print info
        run: |
          echo "USER: "$(whoami)
          echo "PWD: "$(pwd)
          ls -la
          echo "HOME: "$HOME
          docker --version
      - name: Checkout megaboom
        uses: actions/checkout@v4
      - name: Lint Bazel files
        run: bazel mod tidy && git diff --exit-code
      - name: Build local stage targets - tag_array_64x184
        env:
          TARGET: tag_array_64x184
          STAGES: synth floorplan place cts
        run: .github/scripts/build_local_target.sh
      - name: Build local stage targets - L1MetadataArray
        env:
          TARGET: L1MetadataArray
          STAGES: synth floorplan place
        run: .github/scripts/build_local_target.sh
